### ISSUE TITLE
Run SerialPortEventListener in other Thread

### ISSUE THREAD

**Issue by Tsyklop** [nyholku/purejavacomm#102]
Hi.

Can your make run SerialPortEventListener in new thread?

Thanks.

**Comment by nyholku** [comment]
Please elaborate I do not understand what you want to do.

**Comment by Tsyklop** [comment]
@nyholku now SerialPortEventsListener starts in one thread. I'm doing the Swing application and before I display the window I connect to the system, but due to the fact that the SerialPortEventsListener starts in the same thread, the whole process stops on the SerialPortEventsListener and the program does not go any further.

**Comment by Tsyklop** [comment]
@nyholku for example librarry [JSSC](https://github.com/scream3r/java-simple-serial-connector) run Listenere in new Thread and program run success.

**Comment by nyholku** [comment]
Hmm, not sure I still understand the problem. PJC creates an internal thread for each open port and the SerialPortEventListener gets called from that thread, so unless you block inside the SerialPortEventListener event handling everything should be ok. If you need to do Swing stuff from within the SerialPortEventListener you should use swing utilities invoke methods.

**Comment by Tsyklop** [comment]
I check again. Sorry. my mistake.
