### ISSUE TITLE
Non-responsive bluetooth serial port hangs application 

### ISSUE THREAD

**Issue by GlennED** [nyholku/purejavacomm#106]
The following is a code snippet from the CommPortIdentifier class method open:

if (info != null)
	port = info.m_Driver.getCommPort(m_PortName, info.m_PortType);
else
	port = new PureJavaSerialPort(m_PortName, timeout); // FIXME timeout here is not used

The following code snippet from the PureJavaSerialPort class:

        PureJavaSerialPort(String name, int timeout) throws PortInUseException {
		super();

		boolean usepoll = false;
		if (JTermios.canPoll()) {
			String key1 = "purejavacomm.use_poll";
			String key2 = "purejavacomm.usepoll";
			if (System.getProperty(key1) != null) {
				usepoll = Boolean.getBoolean(key1);
				log = log && log(1, "use of '%s' is deprecated, use '%s' instead\n", key1, key2);
			} else if (System.getProperty(key2) != null)
				usepoll = Boolean.getBoolean(key2);
			else
				usepoll = true;
		}
		USE_POLL = usepoll;

		RAW_READ_MODE = Boolean.getBoolean("purejavacomm.rawreadmode");

		this.name = name;

		int tries = (timeout + 5) / 10;
		while ((m_FD = open(name, O_RDWR | O_NOCTTY | O_NONBLOCK)) < 0) {
			int errno = errno();
			try {
				Thread.sleep(10);
			} catch (InterruptedException e) {
				e.printStackTrace();
				Thread.currentThread().interrupt();
			}
			if (tries-- < 0)
				throw new PortInUseException("Unknown Application", errno);
		}

It appears that the "timeout" value is 3000 and this results in the "tries" to be 300. Since a bluetooth port does not respond when the bluetooth device is off it takes an extremely long time to return from the "open" method. The comment "FIXME timeout here is not used" suggests that the "tries" value can be passed as an argument instead of the "timeout" parameter.

I will try this myself but if you know any reason why this is not a good idea please let me know. Thanks.

**Comment by nyholku** [comment]
Hi,

I think that comment is outdated as clearly 'timeout' is used in the code to calculate 'tries'. I suggest you try timeout 0 this will get you timeout after the first try fails which is probably what you want with bluetooth devices.

**Comment by johnstosh** [comment]
FYI, the code can be changed to calculate the elapsed time instead of
assuming that the open call takes zero time.

I can write an example if that would explain better.

**Comment by nyholku** [comment]
Sure it can but I'm not sure it is worth the risk of changing that code which works for many. IIRC in Windows it sometimes takes about ten calls to open a port when you are re-opening the port. So while it would look perfectly safe to just change the loop logic to calculate the time I'm slightly hesitant to change that. If you make a pull request I will consider it.

**Comment by GlennED** [comment]
If there was some way in advance to determine if the serial port is "bluetooth" then it would be possible to change the timeout value to 0 for just the "bluetooth" serial ports. I need to support a mix of physical rs-232 serial ports, USB virtual serial ports and bluetooth serial ports.

**Comment by nyholku** [comment]
That would be great but alas I know of no easy method to do that in Windows let alone all the other platforms....

**Comment by GlennED** [comment]
I am interested in seeing your example code to experiment with this improvement.
Thanks.

**Comment by johnstosh** [comment]
At our office, when waiting on hardware, we will use
System.currentTimeMillis() like the following

    PureJavaSerialPort(String name, int timeout) throws PortInUseException {
        super();

        boolean usepoll = false;
        if (JTermios.canPoll()) {
            String key1 = "purejavacomm.use_poll";
            String key2 = "purejavacomm.usepoll";
            if (System.getProperty(key1) != null) {
                usepoll = Boolean.getBoolean(key1);
                log = log && log(1, "use of '%s' is deprecated, use '%s'
instead\n", key1, key2);
            } else if (System.getProperty(key2) != null) {
                usepoll = Boolean.getBoolean(key2);
            } else {
                usepoll = true;
            }
        }
        USE_POLL = usepoll;

        RAW_READ_MODE = Boolean.getBoolean("purejavacomm.rawreadmode");

        this.name = name;

        long before = System.currentTimeMillis();
        int tries = (timeout + 5) / 10;
        while ((m_FD = open(name, O_RDWR | O_NOCTTY | O_NONBLOCK)) < 0) {
            int errno = errno();

            try {
                Thread.sleep(10);
            } catch (InterruptedException e) {
                e.printStackTrace();
                Thread.currentThread().interrupt();
            }

            // old way
            if (tries-- < 0) {
                throw new PortInUseException("Unknown Application", errno);
            }

            // new way
            long after = System.currentTimeMillis();
            if (after - before > timeout) {
                throw new PortInUseException("Unknown Application", errno);
            }
        }

    }





--
Johnny Muczynski
734-262-2045

**Comment by GlennED** [comment]
John,

I have tried your solution and it works perfectly. I don’t believe that there are any potential negative side-effects.

**Comment by nyholku** [comment]
More precisely I'm concerned about the possibilities things I cannot see! 

This approach looks "  long after = System.currentTimeMillis(); if (after - before > timeout)" looks perfectly reasonable and difficult to see how that could fail.

However, when I wrote that code I had a reason to code it the way it was coded and I'm slightly concerned if the 'new' way is 100% compatible with old way.

But it is difficult to say how the 'new' way could cause problems for old users.

**Comment by GlennED** [comment]
Thanks everyone for your help with this issue.
