### ISSUE TITLE
GitHub code out of date

### ISSUE THREAD

**Issue by swarwick** [nyholku/purejavacomm#116]
Can you get an update to github so we are all on the same source and can talk about the issues with the same source code.

**Comment by nyholku** [comment]
Ill try to do that over the weekend.

**Comment by swarwick** [comment]
Any word on getting the code up to date?

**Comment by nyholku** [comment]
I just pushed 1.0.2 rebranded as 1.0.3 cause I could not be sure that the 1.0.2 binaries out there were 100% compatible with my local and github source code. But now everything is hopefully in sync.
