### ISSUE TITLE
read() on Windows might incorrectly block forever

### ISSUE THREAD

**Issue by ytai** [nyholku/purejavacomm#47]
First of all - good job on getting a lot of the Linux / OSX quirks out of the way! This one feels a lot better.
To me, especially the ability to cleanly exit a blocked reader when the port is closed was a pain and it seems to work flawlessly now. Previously to work around that issue, I would set a timeout on the reading and wrap the InputStream with a retry loop that would give up when closed. I was now going to get rid of this hack, but then ran into another problem: sometimes my read()s would block forever despite having pending data.
I investigated a little and found a problematic race condition in JTermiosImpl (Windows). Apparently, you are aware of it, since the code and the comments indicated that you tried to work around the fact that Windows would only give you "new data" notifications, as opposed to "have data" (a common problem with edge-triggered vs. level-triggered events). If data arrives between the time you poll and the time you WaitForMultipleObjects, you'll miss the event. However, the way you've worked around it relied on the user-set timeout - you'll block the client way more than necessary, or even worse (such as in my case) - forever! I'm not a Windows API expert, so I cannot advise you on a cleaner solution as far as this goes. However, at least on the Java front you can do better:

deadline = now + user timeout
do {
  if (poll for events) break
  timeout = min(MAX_LAG, deadline - now)
  WaitForMultipleObjects(..., timeout)
} while (now < deadline)

// We will get here at most MAX_LAG time after an event occurred or deadline expired.

This is not very elegant, but at least obviously correct.

Keep up the good work!!!

**Comment by nyholku** [comment]
Closing this for now as I've not heard back from anyone for a while -- feel free to re-open
