### ISSUE TITLE
Can not open Ports with more than one digit in it

### ISSUE THREAD

**Issue by Lauchi** [nyholku/purejavacomm#53]
Hi,

I have got a device with 16 serial ports over TCP/IP (Moxa Nport 6530) wich appear as ordinary comports on my Windows PC. I tried the whole day to get to open the ports with two digits but I can not get it to work. On the line 838 is also a FIXIT marker, maybe somebody knows this issue? I tried to figure out if it could be a overflow of a c-string or the regex for getting the comports is wrong, but none of that helped. Anybody has an idea?

 This is the log:

Try open: COM10
log: call CreateFileW, class 'jtermios.JTermios$JTermiosLogging', line 389
log: CreateFileW(COM10, 0xC0000000, 0x00000000, null, 0x00000003, 0x40000000,null) => opaque@0xffffffffffffffff
log: call GetLastError, class 'jtermios.JTermios$JTermiosLogging', line 389
log: GetLastError() => 2
log: call FormatMessageW, class 'jtermios.JTermios$JTermiosLogging', line 389
log: FormatMessageW(00001200,     null, 2, 1024, allocated@0xd4cb500 (2048 bytes), 2048, null  ) => 44
log: fail() class 'jtermios.windows.JTermiosImpl', line 388, Windows GetLastError()= 2, The system cannot find the file specified.

Port in use or not available: COM10
log: call QueryDosDeviceW, class 'jtermios.JTermios$JTermiosLogging', line 389
log: QueryDosDeviceW(null,[C@11d7d5ee,8192) => 0
log: call QueryDosDeviceW, class 'jtermios.JTermios$JTermiosLogging', line 389
log: QueryDosDeviceW(null,[C@711e0568,16384) => 11014
log: call GetLastError, class 'jtermios.JTermios$JTermiosLogging', lipurejavacomm.PortInUseException
	at purejavacomm.PureJavaSerialPort.<init>(PureJavaSerialPort.java:838)
	at purejavacomm.CommPortIdentifier.open(CommPortIdentifier.java:98)
	at Communication.TelegramSender.openCommport(TelegramSender.java:91)
	at Multiplexer.Multiplexer.<init>(Multiplexer.java:35)
	at Multiplexer.Multiplexer.getInstance(Multiplexer.java:57)
	at Model.Model.initializeMultiplexer(Model.java:95)
	at BGTest.Main.main(Main.java:19)
ne 389
log: GetLastError() => 0

But so far: extremely nice library, using it a lot :)

**Comment by nyholku** [comment]
Been two weeks now and no response and the original code looks like it should work so I'm closing this, feel free to re-open if you have something to report.
