### ISSUE TITLE
purejavacomm support in JDK 1.7 32 bit

### ISSUE THREAD

**Issue by VipinMca** [nyholku/purejavacomm#56]
Does purejavacomm APIs support with JDK 32 bit?

**Comment by nyholku** [comment]
> On 20 Jul 2015, at 15:03, VipinMca <notifications@github.com> wrote:
> 
> Does purejavacomm APIs support with JDK 32 bit build?
> 
> —
> Reply to this email directly or view it on GitHub.
> 


On which platform?

Regardless, I think PJC is mostly 32/64 bit agnostic so it 
should "just work”.

br Kusti
