### ISSUE TITLE
Flushing of RX and TX

### ISSUE THREAD

**Issue by jpvdmerwe** [nyholku/purejavacomm#75]
Hi,

Is it possible to flush the RX and TX, use case for this is when a serial port device is removed and reinserted into same serial port thus causing corrupt data.

**Comment by nyholku** [comment]
I think would be possible, even trivial, to implement but JavaComm spec does not 'allow' for that so I have no plan to add that as PJC's stated goal is to be a drop in replacement for JavaComm / RXTX. Having said that, adding a new method to SerialPort class would not directly make PJC incompatible, but would of course induce non-standard usage making code written for PJC not compatible with JavaComm / RXTX. 

Meanwhile most protocols should handle garbage anyway as serial communication is not 100% reliable.

**Comment by jpvdmerwe** [comment]
Thanks for the feedback.

Am I correct in my logic:
1. Close Serial Port
2. Set Input and Output buffers to 0
3. Sleep thread for 50 ms.
4. Open Serial Port and set both buffers to 8192.

**Comment by nyholku** [comment]
Sorry, I'm not following you, what input/output buffers where are you talking about?

**Comment by johnstosh** [comment]
I think he means the buffer sizes.
That's a nice idea, but seeing them to 0 might get you in trouble. You
might set them to 16 or something and then read any characters that are
sitting in the input buffer.

Having said that, I was able to get my stuff working without changing the
buffer sizes. I just read and thru away garbage. I also changed the
protocol so that there would be synchronization characters.

Johnny

**Comment by nyholku** [comment]
Yeah, well the buffer size is a no-op in PJC, according to JavaComm spec support for it is optional and even when implemented it is not clear what it should do. IIRC on Linux/Unix/Mac OS X I don't know how this could be implemented, in Windows there is some API call to effect this (I suspect that is why it is in the spec and that is why it is optional).

And just like ' johnstosh' when I need to clear the buffer I just read out the garbage, and every serial protocol needs to have means to determine proper data from garbage and synchronise with it so the garbage is mostly a moot point anyway,
