### ISSUE TITLE
Release Tags?

### ISSUE THREAD

**Issue by sitec-mast** [nyholku/purejavacomm#81]
Hi,

is planed to tag releases, e.g. Version 1.0.0?

Best regards

**Comment by nyholku** [comment]
Sorry, what do you mean by release tags? You mean that PJC should have some commit name convention that identified released versions?

**Comment by sitec-mast** [comment]
yes

**Comment by leif81** [comment]
You could use just ordinary git tags or the slightly fancier github releases https://github.com/blog/1547-release-your-software

**Comment by yeroc** [comment]
+1

Without tags in the git repo it's not easy to match up the code that we're running with the actual source code.

**Comment by nyholku** [comment]
Just created my first release tag!
