### ISSUE TITLE
Publish to Maven Central.

### ISSUE THREAD

**Issue by yeroc** [nyholku/purejavacomm#82]
Are you open to publishing releases to Maven Central?  

I know you have your own repository but it makes things easier for consumers of the library to use Maven Central and there's overhead in pulling libraries from multiple repositories.  Also, we know that Maven Central won't go away any time soon but it would be possible for your domain to expire etc.

Sonatype has good [documentation](http://central.sonatype.org/pages/ossrh-guide.html) on the steps involved.

Thanks!

**Comment by nyholku** [comment]
I'm travelling at the moment, I'll get back on beginning of May.

**Comment by SamCooper** [comment]
I'm also keen to see this thanks.

**Comment by purejavacomm** [comment]
Hi, 
I had a go at this (publishing to Maven Central) and got as far as creating the `groupId` 👍 

https://issues.sonatype.org/browse/OSSRH-27013

but having gone through the documentation it seems to me that this is going to use more of my time than I'm willing to put into this. 

So unless someone steps up with a more or less complete pull request that accomplishes this, then this is not going to happen anytime soon, so I'm closing this.

Feel free anyone to open this again if you have something to contribute.

**Comment by purejavacomm** [comment]
Ooops, I just remembered/noticed the pull request by masterav10, I will have a look at that.

**Comment by nyholku** [comment]
I may have succeeded in publishing to a sonatype manven central. Please test if you can access it.

FWIW, this is what the Nexus Repository Manager shows for 'maven':

<dependency>
  <groupId>com.github.purejavacomm</groupId>
  <artifactId>purejavacomm</artifactId>
  <version>1.0.1.RELEASE</version>
</dependency>

**Comment by masterav10** [comment]
As a matter of fact, you did solve it. Just tested using maven central through gradle, and I was able to download using the new groupId. I'm going to make a pull request to update the README to show both gradle and maven links.

**Comment by nyholku** [comment]
Great, hope it helps people who use Maven / Gradle. Thank you very much for your, like I said, this would not have happened without your contribution. Even with that it more time than I had anticipated.
