### ISSUE TITLE
BUG in wait-for-at-least-1-byte behavior (settings for COMMTIMEOUTS are inconsistent with the semantics in javax.comm.CommPort.getInputStream)

### ISSUE THREAD

**Issue by jason-s** [nyholku/purejavacomm#85]
From the [COMMTIMEOUTS](https://msdn.microsoft.com/en-us/library/aa363190%28v=vs.85%29.aspx) documentation:

>Remarks
>If an application sets ReadIntervalTimeout and ReadTotalTimeoutMultiplier to MAXDWORD and sets ReadTotalTimeoutConstant to a value greater than zero and less than MAXDWORD, one of the following occurs when the ReadFile function is called:
>- If there are any bytes in the input buffer, ReadFile returns immediately with the bytes in the buffer.
>- If there are no bytes in the input buffer, ReadFile waits until a byte arrives and then returns immediately.
>- If no bytes arrive within the time specified by ReadTotalTimeoutConstant, ReadFile times out.

This is the behavior I really would like, but it looks like there's no mechanism in PJC to get this. I can either get a timeout that waits for N bytes requested, or a timeout that applies to the delay between characters. (ref: https://github.com/nyholku/purejavacomm/blob/master/src/jtermios/windows/JTermiosImpl.java#L734 )

Does this type of behavior have an equivalent in Linux / OSX? If so, is there any way to enable it in PJC? I'm guessing changing the API is bad, but maybe you could add a new `interface` that adds extended features, and let the various JTermiosImpl classes implement that interface.

**Comment by jason-s** [comment]
Actually, I wonder if there's a bug in JTermiosImpl (at least for Windows).

The [javax.comm.CommPort API says this](https://docs.oracle.com/cd/E17802_01/products/products/javacomm/reference/api/javax/comm/CommPort.html#getInputStream()):

<table border="1">

 <tr>
 <th colspan=2>Threshold</th>
 <th colspan=2>Timeout</th>
 <th rowspan=2>Read Buffer Size</th>
 <th rowspan=2>Read Behaviour</th>
 </tr>

 <tr>
 <th>State</th>
 <th>Value</th>
 <th>State</th>
 <th>Value</th>
 </tr>

 <tr>
 <td>
 disabled
 </td>
 <td>
 -
 </td>
 <td>
 disabled
 </td>
 <td>
 -
 </td>
 <td>
 n bytes
 </td>
 <td>
 block until any data is available
 </td>
 </tr>

 <tr>
 <td>
 enabled
 </td>
 <td>
 m bytes
 </td>
 <td>
 disabled
 </td>
 <td>
 -
 </td>
 <td>
 n bytes
 </td>
 <td>
 block until min(<I>m</I>,<I>n</I>) bytes are available
 </td>
 </tr>

 <tr>
 <td>
 disabled
 </td>
 <td>
 -
 </td>
 <td>
 enabled
 </td>
 <td>
 x ms
 </td>
 <td>
 n bytes
 </td>
 <td>
 block for <I>x</I> ms or until any data is available
 </td>
 </tr>

 <tr>
 <td>
 enabled
 </td>
 <td>
 m bytes
 </td>
 <td>
 enabled
 </td>
 <td>
 x ms
 </td>
 <td>
 n bytes
 </td>
 <td>
 block for <I>x</I> ms or until min(<I>m</I>,<I>n</I>) bytes are available
 </td>
 </tr>

 </table>

I want the "block for x ms or until any data is available" behavior. (which means I should use threshold=disabled, timeout=x) But the way this is implemented in windows/JTermiosImpl, I get this:

{code}
			if (vmin == 0 && vtime > 0) {
				// VMIN = 0 and VTIME > 0 => timed read, return as soon as data is
				// available, VTIME = total time
				touts.ReadIntervalTimeout = 0;
				touts.ReadTotalTimeoutConstant = vtime;
				touts.ReadTotalTimeoutMultiplier = 0;
			}
{code}

And that's not right, this will wait x msec for the N bytes requested, and if I get some smaller number of bytes, it will *not* return as soon as data is available.

**Comment by nyholku** [comment]
Are you sure? Have you tested that?

IIRC one of my test cases should cover this and the when I developed the code I'm sure I tried this case too. 

Of course it is possible that it is a bug.

Contributions to demonstrate this with a test case and a fix are welcome ...

**Comment by jason-s** [comment]
test case written, on my way to work now to try it...

**Comment by jason-s** [comment]
Test program: https://gist.github.com/jason-s/6e39547d3aa58a3e605b551c163bbb47

I ran it with PJC 0.0.22 and the odd thing is that it doesn't set the COMMTIMEOUTS the way I'd expect (and the end behavior is different too); the `vmin` variable is usually set to a positive number; it's not being set to 0 if `disableReceiveTimeout()` is called:

```
C:\>java -jar c:/tmp/bugs/pjc85test/pjc-85-test.jar com28 115200 1000 false
log: instantiating jtermios.windows.JTermiosImpl
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
comm port=com28, baudrate = 115200, rxtimeout=1000, rxthreshold=null
log: vmin 1 vtime 1000 ReadIntervalTimeout 1000 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
73999 wrote 8 bytes
74003 read  8 bytes
74251 wrote 8 bytes
74259 read  8 bytes
74503 wrote 8 bytes
74515 read  8 bytes
```

```
C:\>java -jar c:/tmp/bugs/pjc85test/pjc-85-test.jar com28 115200 1000 1
log: instantiating jtermios.windows.JTermiosImpl
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
comm port=com28, baudrate = 115200, rxtimeout=1000, rxthreshold=1
log: vmin 1 vtime 1000 ReadIntervalTimeout 1000 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
29668 wrote 8 bytes
29673 read  8 bytes
29920 wrote 8 bytes
29928 read  8 bytes
30172 wrote 8 bytes
30184 read  8 bytes
```

```
C:\>java -jar c:/tmp/bugs/pjc85test/pjc-85-test.jar com28 115200 1000 0
log: instantiating jtermios.windows.JTermiosImpl
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
comm port=com28, baudrate = 115200, rxtimeout=1000, rxthreshold=0
93449 read  0 bytes
93450 wrote 8 bytes
93451 read  0 bytes
93452 read  0 bytes
93453 read  0 bytes
93455 read  8 bytes
93456 read  0 bytes
93458 read  0 bytes
93459 read  0 bytes
93461 read  0 bytes
```

```
C:\>java -jar c:/tmp/bugs/pjc85test/pjc-85-test.jar com28 115200 1000 32
log: instantiating jtermios.windows.JTermiosImpl
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
comm port=com28, baudrate = 115200, rxtimeout=1000, rxthreshold=32
log: vmin 32 vtime 1000 ReadIntervalTimeout 1000 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
54618 wrote 8 bytes
54872 wrote 8 bytes
55123 wrote 8 bytes
55375 wrote 8 bytes
55388 read  32 bytes
55390 read  0 bytes
55627 wrote 8 bytes
55879 wrote 8 bytes
56131 wrote 8 bytes
56383 wrote 8 bytes
56396 read  32 bytes
56398 read  0 bytes
56635 wrote 8 bytes
56887 wrote 8 bytes
57138 wrote 8 bytes
```

**Comment by jason-s** [comment]
looks like there is a bug in PureJavaSerialPort.java in `read()`:

```
if (m_TimeoutThresholdChanged) { // does not need the lock if we just check the value
							synchronized (m_ThresholdTimeoutLock) {
								int vtime = m_ReceiveTimeoutEnabled ? m_ReceiveTimeoutVTIME : 0;
								int vmin = m_ReceiveThresholdEnabled ? m_ReceiveThresholdValue : 1;   // <----
								synchronized (m_Termios) {
									m_Termios.c_cc[VTIME] = (byte) vtime;
									m_Termios.c_cc[VMIN] = (byte) vmin;
									checkReturnCode(tcsetattr(m_FD, TCSANOW, m_Termios));
								}
								m_TimeoutThresholdChanged = false;
							}
						}
```

Shouldn't it be

    int vmin = m_ReceiveThresholdEnabled ? m_ReceiveThresholdValue : 0;

Otherwise it looks like there is no way to set vtime > 0 and vmin = 0.

**Comment by jason-s** [comment]
same behavior using HEAD (rev 9a8b77735a8fb0d27ddfb4bbb0187e85488b42f2) 

If I make the above change

    int vmin = m_ReceiveThresholdEnabled ? m_ReceiveThresholdValue : 0;

and also change

							if (im_ReceiveThresholdEnabled)
								minBytesRequired = im_ReceiveThresholdValue; // BEST
							else
								minBytesRequired = 1;

to

							if (im_ReceiveThresholdEnabled)
								minBytesRequired = im_ReceiveThresholdValue; // BEST
							else
								minBytesRequired = 0;

then when I use enableReceiveTimeout(x) and disableReceiveThreshold(), I get vtime > 0 and vmin = 0, and the behavior I expect from the Windows API:

```
C:\>java -jar c:/tmp/bugs/pjc85test/pjc-85-test.jar com28 115200 1000 false
log: instantiating jtermios.windows.JTermiosImpl
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalTimeoutMultiplier 0
comm port=com28, baudrate = 115200, rxtimeout=1000, rxthreshold=null
log: vmin 0 vtime 1000 ReadIntervalTimeout 0 ReadTotalTimeoutConstant 1000 ReadTotalTimeoutMultiplier 0
32427 wrote 8 bytes
32679 wrote 8 bytes
32931 wrote 8 bytes
33183 wrote 8 bytes
33433 read  32 bytes
33435 read  0 bytes
33435 wrote 8 bytes
33687 wrote 8 bytes
33939 wrote 8 bytes
34191 wrote 8 bytes
34440 read  32 bytes
34442 read  0 bytes
34443 wrote 8 bytes
34695 wrote 8 bytes
```

which is NOT what is specified in https://docs.oracle.com/cd/E17802_01/products/products/javacomm/reference/api/javax/comm/CommPort.html#getInputStream().

this comment continued...

**Comment by jason-s** [comment]
Then if I make the change in windows/JTermiosImpl.java from

        if (vmin == 0 && vtime > 0) {
            // VMIN = 0 and VTIME > 0 => timed read, return as soon as data is
            // available, VTIME = total time
            touts.ReadIntervalTimeout = 0;
            touts.ReadTotalTimeoutConstant = vtime;
            touts.ReadTotalTimeoutMultiplier = 0;
        }

to

        if (vmin == 0 && vtime > 0) {
            // VMIN = 0 and VTIME > 0 => timed read, return as soon as data is
            // available, VTIME = total time
            touts.ReadIntervalTimeout = MAXDWORD;
            touts.ReadTotalTimeoutConstant = vtime;
            touts.ReadTotalTimeoutMultiplier = MAXDWORD;;
        }

I get this behavior, which is what I expect:

``
C:\>java -jar c:/tmp/bugs/pjc85test/pjc-85-test.jar com28 115200 1000 false
log: instantiating jtermios.windows.JTermiosImpl
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalT
imeoutMultiplier 0
log: vmin 0 vtime 0 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 0 ReadTotalT
imeoutMultiplier 0
comm port=com28, baudrate = 115200, rxtimeout=1000, rxthreshold=null
log: vmin 0 vtime 1000 ReadIntervalTimeout -1 ReadTotalTimeoutConstant 1000 Read
TotalTimeoutMultiplier -1
04398 wrote 8 bytes
04404 read  8 bytes
04650 wrote 8 bytes
04660 read  8 bytes
04902 wrote 8 bytes
04915 read  8 bytes
05154 wrote 8 bytes
05155 read  6 bytes
05171 read  2 bytes
05406 wrote 8 bytes
05411 read  8 bytes
05658 wrote 8 bytes
05667 read  8 bytes
05910 wrote 8 bytes
05923 read  8 bytes
```

Note the subsequence

```
05154 wrote 8 bytes
05155 read  6 bytes
05171 read  2 bytes
```

representing "eager" return from a `read()`, which can happen in certain cases. It also occasionally happens if you use (`ReadIntervalTimeout=N`, `ReadTotalTimeoutMultiplier=0`, `ReadTotalTimeout=0`) rather than  the special case (`ReadIntervalTimeout=MAXDWORD`, `ReadTotalTimeoutMultiplier=MAXDWORD`, `ReadTotalTimeout=N`).

On the surface, this looks like they have identical behavior to the existing PureJavaComm behavior. 
But I am nervous about the use of ReadIntervalTimeout; it seems like it might have some subtle cases where it causes the wrong behavior. I can't seem to find those cases right now, however. I'll keep trying as I have time to do so....

**Comment by nyholku** [comment]
Brilliant, keep working at it!

**Comment by jason-s** [comment]
Oh, p.s. -- this test requires you to have a hardware loopback (feed TX line back into RX line).

I'm using a DLP-USB1232H USB-to-UART (5V TTL) converter. Highly recommended, about US$29 from distributors like Mouser and Digi-Key, and it's rock-solid based on the FTDI chipset. We use it at 4.375Mbaud, very low bit error rates (something like 1 error every 1-10 million bytes or so).

**Comment by jason-s** [comment]
hmmm... note: seems like there needs to be a way to distinguish "disable" from enabled(0) for both timeout and threshold.

**Comment by nyholku** [comment]
Hi, where are we with this fix? I would like to include this with the next release, do the changes you propose above fix this issue?

**Comment by nyholku** [comment]
Closing this as I've not received any feedback.
