### ISSUE TITLE
New release incorporating fixes since 1.0.0

### ISSUE THREAD

**Issue by rhwood** [nyholku/purejavacomm#90]
Can you please release a version incorporating the fixes since 1.0.0 was released?

I would prefer to use an official release, but depend on #80/#84 being fixed.

**Comment by nyholku** [comment]
Done

**Comment by rhwood** [comment]
@nyholku Thank you. BTW, is there a reason you removed 1.0.0 from maven? I'd have thought that both 1.0.0 and 1.0.1 should remain available so that projects pulling 1.0.0 from maven could continue to do until they were ready or able to update to 1.0.1.

**Comment by nyholku** [comment]
> On 1 Oct 2016, at 12:37, Randall Wood <notifications@github.com> wrote:
> 
> @nyholku Thank you. BTW, is there a reason you removed 1.0.0 from maven? I'd have thought that both 1.0.0 and 1.0.1 should remain available so that projects pulling 1.0.0 from maven could continue to do until they were ready or able to update to 1.0.1.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Yeah, that was a mistake, I accidentally overwrote 1.0.0 with 1.0.1 so I removed it to lessen the confusion. I need to check if I have the binaries backed up cause it is a pain to recreate them.

br Kusti

**Comment by rhwood** [comment]
I think the 1.0.0 binaries are in commit 0889a861a417b73836f5a581a8eb922b1bdf394d

**Comment by nyholku** [comment]
Sadly, like I anticipated, the commit does not contain all the maven files. So I had to download the whole project at that point time, recompile and re-deploy with maven. Now it appear that the 1.0.0 files are back but I don't have any way of testing them as I'm not using maven.
