### ISSUE TITLE
Level 6 logging messages

### ISSUE THREAD

**Issue by abencomo** [nyholku/purejavacomm#92]
I’m trying to connect to a [Dynamixel AX-12A](http://www.robotis.us/ax-12a/) servo using a Mac with OSX 10.10.5 and an [USB2Dynamixel](http://support.robotis.com/en/product/auxdevice/interface/usb2dxl_manual.htm) module in TTL mode.  However, it fails with the messages below.  Does anyone know what they mean?

log: 071118,instantiating jtermios.macosx.JTermiosImpl
log: 071120,> open('/dev/tty.usbserial-AI03QD95',00020006)
log: 071123,< open('/dev/tty.usbserial-AI03QD95',00020006) => 16
log: 071124,> tcgetattr(16,jtermios.Termios@a1323da0)
log: 071129,< tcgetattr(16,jtermios.Termios@606b10a3) => 0
log: 071129,> close(16)
log: 071130,< close(16) => 0
log: 071131,> open('/dev/tty.usbserial-AI03QD95',00020006)
log: 071135,< open('/dev/tty.usbserial-AI03QD95',00020006) => 16
log: 071135,> fcntl(16, 3, 0)
log: 071135,< fcntl(16, 3, 0) => 6
log: 071135,> fcntl(16, 4, 2)
log: 071135,< fcntl(16, 4, 2) => 0
log: 071136,> tcgetattr(16,jtermios.Termios@a1323da0)
log: 071138,< tcgetattr(16,jtermios.Termios@606b10a3) => 0
log: 071138,> cfmakeraw(16,jtermios.Termios@606b10a3)
log: 071139,< cfmakeraw(16,jtermios.Termios@60792824)
log: 071139,> tcsetattr(16,0,jtermios.Termios@d87f3705)
log: 071139,< tcsetattr(16,0,jtermios.Termios@d87f3705) => 0
log: 071139,> setspeed(16,jtermios.Termios@d87f3705,9600)
log: 071141,< setspeed(16,jtermios.Termios@d87f3705,9600) => 0
log: 071141,> tcsetattr(16,0,jtermios.Termios@d87f3705)
log: 071141,< tcsetattr(16,0,jtermios.Termios@d87f3705) => 0
log: 071141,> tcsetattr(16,0,jtermios.Termios@d87f3705)
log: 071142,< tcsetattr(16,0,jtermios.Termios@d87f3705) => 0
log: 071142,> ioctl(16,1074033770,[[0]])
log: 071143,< ioctl(16,1074033770,[[38]]) => 0
log: 071143,> pipe([2,0,0])
log: 071143,< pipe([2,17,18]) => 0
log: 071143,> fcntl(17, 3, 0)
log: 071143,< fcntl(17, 3, 0) => 0
log: 071143,> fcntl(17, 4, 4)
log: 071143,< fcntl(17, 4, 4) => 0
Nov 13, 2016 9:41:11 PM gov.nasa.arc.dynamixel.port.SerialPortImpl <init>
INFO: Port open
log: 071160,> setspeed(16,jtermios.Termios@d87f3705,1000000)
log: 071162,< setspeed(16,jtermios.Termios@d87f3705,1000000) => 0
log: 071163,> tcsetattr(16,0,jtermios.Termios@d87f3705)
log: 071163,< tcsetattr(16,0,jtermios.Termios@d87f3705) => 0
log: 071166,> write(16,[6,0xFF,0xFF,0xFE,0x02,0x01,0xFE],6)
log: 071167,< write(16,[6,0xFF,0xFF,0xFE,0x02,0x01,0xFE],6) => 6
log: 071167,> tcsetattr(16,0,jtermios.Termios@b21ed329)
log: 071167,< tcsetattr(16,0,jtermios.Termios@b21ed329) => 0
log: 071168,> select(18,[,,,,,,,,,,,,,,,,16,17],[,,,,,,,,,,,,,,,,,],[,,,,,,,,,,,,,,,,,],jtermios.TimeVal@1e88b3c)
log: 071672,< select(18,[,,,,,,,,,,,,,,,,,],[,,,,,,,,,,,,,,,,,],[,,,,,,,,,,,,,,,,,],jtermios.TimeVal@1e88b3c) => 0
Servos:[]
log: 071679,> write(16,[6,0xFF,0xFF,0xFE,0x02,0x01,0xFE],6)
log: 071680,< write(16,[6,0xFF,0xFF,0xFE,0x02,0x01,0xFE],6) => 6
log: 071680,> select(18,[,,,,,,,,,,,,,,,,16,17],[,,,,,,,,,,,,,,,,,],[,,,,,,,,,,,,,,,,,],jtermios.TimeVal@1e88b3c)
log: 072184,< select(18,[,,,,,,,,,,,,,,,,,],[,,,,,,,,,,,,,,,,,],[,,,,,,,,,,,,,,,,,],jtermios.TimeVal@1e88b3c) => 0

**Comment by nyholku** [comment]
Don't see anything wrong there, what is the problem?

Why have you enabled the logging?

The logging is there to debug PureJavaComm, not to help you to debug your code...

**Comment by nyholku** [comment]
Heard nothing so closing this
